import Head from "next/head";
import NavSwitch from "./NavScwitch";
import styles from '../styles/Header.module.css'

import { navLinks } from "../constants/constants";
import { useState } from "react";
import { HiMenuAlt3, HiOutlineX } from "react-icons/hi";

const Header = () => {
    const [topBar, setTopBar] = useState(false)
    return (
        <>
            <Head>
                <title>Mattias Duarte | Portafolio Web</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="stylesheet" href="https://cdn.rawgit.com/mfd/09b70eb47474836f25a21660282ce0fd/raw/e06a670afcb2b861ed2ac4a1ef752d062ef6b46b/Gilroy.css"></link>
            </Head>

            <header className="sticky top-0  container sm:backdrop-blur-md ">
                <nav className="m-auto flex py-3 items-center justify-between z-50">
                    <div className="flex gap-1 font-bold text-xl">
                        Mattias <span className='text-transparent bg-clip-text bg-gradient-to-r from-primary to-secondary'>Duarte</span>
                    </div>

                    <ul className={`backdrop-blur-xl  ${topBar ? styles.active : ''} ${styles.nav_menu} transition-all`}>
                    {/* <ul className={`z-[1000] flex-col fixed right-0 left-0 top-[${topBar}] h-full backdrop-blur-md items-center justify-center flex gap-5 sm:static sm:bg-transparent sm:flex-row transition-all`}> */}
                        {navLinks.map(link =>
                            <a
                                className="font-semibold text-gray-600 hover:text-gray-900 dark:text-gray-300 dark:hover:text-gray-50 transition-all"
                                href={`#${link.path}`}
                                key={link.path}
                            >
                                {link.name}
                            </a>
                        )}
                        <div className="sm:hidden cursor-pointer text-xl" onClick={() => setTopBar(!topBar)}>
                            <HiOutlineX/>
                        </div>
                    </ul>
                    <div className="flex gap-3">
                        <NavSwitch/>
                        <HiMenuAlt3  className="sm:hidden text-xl cursor-pointer" onClick={() => setTopBar(true)}/>
                    </div>
                </nav>
            </header>
        </>
    )
}

export default Header